import React from "react";

export default function Footer() {
  return (
    <footer className="footer-wrapper">
      <div className="footer-content">
        <div className="footer-disclaimer">
          <span>Frontend UI generated by AI Coding Agent</span>
          <span className="footer-badge">Antigravity Google Gemini 3.7 Flash</span>
        </div>
      </div>
    </footer>
  );
}
